-- Suppression de toutes les tables -- genere le 29/05/2026 15:16:22
-- ATTENTION : supprime toutes les donnees.

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS FT_AUDIT_SITES;
DROP TABLE IF EXISTS FT_SEUILS_SITE;
DROP TABLE IF EXISTS FT_LOGS_CONNEXION;
DROP TABLE IF EXISTS FT_QUEUE;
DROP TABLE IF EXISTS FT_QUEUE_STATUS;
DROP TABLE IF EXISTS FT_QUEUE_LOCK;
DROP TABLE IF EXISTS FT_COMMENTAIRES;
DROP TABLE IF EXISTS FT_LOGS;
DROP TABLE IF EXISTS FT_SITE;
DROP TABLE IF EXISTS FT_DEPARTEMENT;
DROP TABLE IF EXISTS FT_REGION;
DROP TABLE IF EXISTS FT_INTERREGION;
DROP TABLE IF EXISTS FT_SEUILS;
DROP TABLE IF EXISTS FT_COMPTES;
DROP TABLE IF EXISTS FT_CONFIG_SPEEDTEST;

SET FOREIGN_KEY_CHECKS = 1;
